**Muhammad Abdullah(413846) BSCS 12A**

In [ ]:
print("Hello, Machine Learning World!")

Hello, Machine Learning World!


In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
a = 3
b = 5
print(a+b)

8


In [15]:
from google.colab import drive
drive.flush_and_unmount()

In [16]:
import numpy as np

In [18]:
data = np.array([4.0,5.0,6.0,8.0,10.0])
normalized_data =  (data - np.mean(data))/np.std(data)
print(normalized_data)

[-1.2070197  -0.74278135 -0.27854301  0.64993368  1.57841037]


In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
result = np.dot(A,B)
print(result)


[[19 22]
 [43 50]]


In [20]:
X = np.array([[1,2],[3,4],[5,6]])
beta = np.array([0.5,1.5])
b = 0.1
y_pred = np.dot(X,beta) + b
print(y_pred)

[ 3.6  7.6 11.6]


In [21]:
import numpy as np
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result = array_a + array_b
print(result)


[5 7 9]


In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [23]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a+b)

[[2 4 6]
 [5 7 9]]


In [24]:
a = np.array([1,2,3,4,5,6])
a_reshaped = a.reshape(2,3)
print(a_reshaped)

[[1 2 3]
 [4 5 6]]


In [25]:
a_flat = a_reshaped.flatten()
print(a_flat)

[1 2 3 4 5 6]


In [26]:
array_1d = np.array([10,20,30,40])
print(array_1d)

[10 20 30 40]


In [27]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
array_sum = array_1d + 5
print(array_sum)

[15 25 35 45]


In [29]:
random_matrix = np.random.random((3,3))
print(random_matrix)

[[0.62305493 0.97374066 0.2356063 ]
 [0.48362364 0.94174212 0.04849621]
 [0.69992364 0.83077265 0.00959603]]


In [30]:
random_matrix_scaled =random_matrix * 100
print(random_matrix_scaled)

[[62.30549288 97.37406644 23.56063028]
 [48.36236392 94.17421194  4.84962082]
 [69.99236366 83.07726493  0.95960321]]


In [31]:
reshaped_array = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [32]:
sliced_array = reshaped_array[:2, :2]
print(sliced_array)

[[1 2]
 [4 5]]


In [35]:
def normalize_func(arr):
  arr_min = np.min(arr)
  arr_max = np.max(arr)
  normalized_arr = (arr-arr_min)/(arr_max - arr_min)
  return normalized_arr

random_arr = np.random.random((4,4)) * 100
normalized_array = normalize_func(random_arr)
print("Actual Array :\n" ,random_arr)
print("Normalized Array :\n" ,normalized_array)

Actual Array :
 [[67.95541978 71.08165307 59.07404651 83.48062827]
 [78.08164792 51.02554407 90.14658872 41.32275264]
 [10.83949777 36.37677033  3.15667885  7.79723706]
 [30.10656647 34.69693758 76.4446366  51.39263192]]
Normalized Array :
 [[0.74489951 0.78083739 0.64280292 0.92337088]
 [0.86130643 0.55028066 1.         0.43874139]
 [0.08831851 0.38188442 0.         0.05334594]
 [0.30980475 0.36257376 0.84248803 0.55450055]]
